server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://smartcampus_user:smartcampus123@smart-campus-cluster.hetf8xd.mongodb.net/?appName=smart-campus-cluster
      database: smart_campus

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smart_campus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 693740394599-2eifb8c79skvk60da7kvofqot3197et4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

app:
  jwt:
    secret: smartcampus_jwt_secret_key_2026_very_long_secure_string
    expiration: 86400000