server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://smartcampus_user:smartcampus123@smart-campus-cluster.hetf8xd.mongodb.net/?appName=smart-campus-cluster
      database: smart_campus

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: REPLACE_WITH_YOUR_GOOGLE_CLIENT_ID
            client-secret: REPLACE_WITH_YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile

app:
  jwt:
    secret: smartcampus_jwt_secret_key_2026_very_long_secure_string
    expiration: 86400000